export enum HOLIDAY_STATUS {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum USER_ROLE {
  ADMIN = "ADMIN",
  HUMAN_RESOURCE = "HUMAN_RESOURCE",
  EMPLOYEE = "EMPLOYEE",
}

export enum COLOR_THEME{
  RED = 'RED',
  BLUE = 'BLUE',
}